import type { Metadata } from "next";
import "./../../app/globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DamagaLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <AppSidebar /> {/* Sidebar tetap di kiri */}
      <main>
        <SidebarTrigger />
        {/* Konten utama */}
        {children}
      </main>
    </SidebarProvider>
  );
}
